### PR TITLE
Oh man

### PR DESCRIPTION
**Pull request by eeclaire**
When I'm through with this, it's going to be so great.

### CODE REVIEW

**Comment by eeclaire** [comment]
LOL WHY

DENY THAT SHIT. STRAIGHT UP.

**Comment by ZacharyThomas** [comment]
Bill.jpg: Trumpkin

**Comment by eeclaire** [comment]
I WANTED IT JUST TO BE THAT PICTURE OF BILL BUT THEN I DECIDED THAT PUTTING
THAT ON A PUBLIC WEBSITE IS NOT RESPECTFUL OF PERSONAL BOUNDARIES AND
PROBABLY A LITTLE ILLEGAL.

**Comment by ZacharyThomas** [comment]
Pretty sure it's not illegal but potentially weird. Trumpkin is a
legitimate choice.

**Comment by eeclaire** [comment]
It only felt fair

**Comment by ZacharyThomas** [comment]
1/4th of the way to DO (maybe?)

**Comment by eeclaire** [comment]
What is DO?

**Comment by ZacharyThomas** [comment]
Digital Ocean. Your shit may still yet be coming!

**Comment by eeclaire** [comment]
Ahaha well, if there's one thing I can aim for. My SoP for grad school will condense down to "I'm here for the free T-shirts"

**Pull request merged**
